name: Publish
on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish sys
        run: cargo publish --token ${CRATES_TOKEN} -p unity_native_sys
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish macros
        run: cargo publish --token ${CRATES_TOKEN} -p unity_native_proc_macro
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish main lib
        run: cargo publish --token ${CRATES_TOKEN} -p unity_native
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
